// <auto-generated />
namespace HTML_Parser.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixedTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201812171829384_FixedTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
